### PR TITLE
Feature/te 411 rename testcase

### PR DESCRIPTION
**Pull request by kpanier**
Rename testcase from navigator

### CODE REVIEW

**Comment by franzbecker** [comment]
We should use the mechanisms provided by Xtext in order to improve the refactoring support.

Have a look at `AbstractTclUiModule`:

```
	// contributed by org.eclipse.xtext.xtext.generator.ui.refactoring.RefactorElementNameFragment2
	public Class<? extends IRenameRefactoringProvider> bindIRenameRefactoringProvider() {
		return JvmRenameRefactoringProvider.class;
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.ui.refactoring.RefactorElementNameFragment2
	public Class<? extends IRenameStrategy.Provider> bindIRenameStrategy$Provider() {
		return JvmMemberRenameStrategy.Provider.class;
	}
		
```

We should probably adapt `JvmMemberRenameStrategy`

**Comment by kpanier** [comment]
We use the refactoring support from xtext. In the TclUiModule we return an IRenameStrategy which is used by the shortcut SHIFT - ALT + R. The TClRenameStrategy only checks that the tcl file in the file system is also renamed, to avoid an error. 
The xtend tooling implementation works the same way.

i didn't find any solution in the xtext documentation to start a rename action on a file system. I also didn't want to drop out the normal rename operation for non model files.  So there is a custom RenameAction to delegate rename to normal file rename operation or to xtext rename. 
Calling the rename strategy of the xtext stuff over IRenameSupport.Factory and IRenameContextFactory is not the docuemented way, but I didn't find a documented way for this.

**Comment by franzbecker** [comment]
I looked into it a bit more detailed and disagree with the proposed solution.

What we should do is to implement a rename participant that adds the change.

http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fextension-points%2Forg_eclipse_ltk_core_refactoring_renameParticipants.html&cp=2_1_1_103
http://stackoverflow.com/questions/6618495/eclipse-rename-refactoring-override

Xbase adds one for itself that is only activated if you try to rename the generated source file. The code is a bit complex but can be found here: `org.eclipse.xtext.common.types.ui.refactoring.participant.JdtRenameParticipant`

We should do this by adding a class `org.testeditor.tcl.dsl.ui.refactoring.TclRenameParticipant` and register it at the given extension point.

To the plugin.xml we would need to add the following:
```
	<extension
		point="org.eclipse.ltk.core.refactoring.renameParticipants">
		<renameParticipant
			class="org.testeditor.tcl.dsl.ui.TclExecutableExtensionFactory:org.testeditor.tcl.dsl.ui.refactoring.TclRenameParticipant"
			id="org.testeditor.tcl.dsl.ui.renameParticipant"
			name="Rename Participant">
		    <enablement>
		       <with variable="affectedNatures">
		          <iterate operator="or">
		             <equals value="org.eclipse.jdt.core.javanature"/>
		          </iterate>
		       </with>
		    </enablement>
		</renameParticipant>
	</extension>
```
The enablement is not optimal yet but can be refined. Especially it should only be enabled if we do have a TCL element.

Here is some hacky rename participant to show how it can look like:
```
import static org.testeditor.dsl.common.CommonPackage.Literals.*

import static extension org.eclipse.xtext.nodemodel.util.NodeModelUtils.findNodesForFeature

class TclRenameParticipant extends RenameParticipant {

	IFile element

	override checkConditions(IProgressMonitor pm, CheckConditionsContext context) throws OperationCanceledException {
		// TODO check the validity of the new name
	}

	override createChange(IProgressMonitor pm) throws CoreException, OperationCanceledException {
		val editor = getXtextEditor()
		val test = getTestCase(editor)

		val node = test.findNodesForFeature(NAMED_ELEMENT__NAME).head
		val nameReplacement = new ReplaceEdit(node.offset, node.length, arguments.newName.replaceFirst("\\.(tcl|tml|config)", ""))

		val change = new EditorDocumentChange("Change name", editor, false)
		change.setEdit(nameReplacement)

		return change
	}

	private def XtextEditor getXtextEditor() {
		val ref = new AtomicReference
		Display.^default.syncExec [
			val window = PlatformUI.workbench.workbenchWindows.head
			val editorPart = IDE.openEditor(window.activePage, element)
			ref.set(EditorUtils.getXtextEditor(editorPart))
		]
		return ref.get
	}

	private def TestCase getTestCase(XtextEditor editor) {
		editor.document.readOnly [ resource |
			val tclModel = resource.contents.filter(TclModel).head
			return tclModel?.test
		]
	}

	override getName() {
		return "Tcl Renaming"
	}

	override protected initialize(Object element) {
		if (element instanceof IFile) {
			this.element = element
			return true
		}
		return false
	}

}
```

**Comment by franzbecker** [comment]
If you agree we should start over on a new branch.

**Comment by kpanier** [comment]
You can try it. But from my opinion, we have actual no refactoring menu in the cnf based explorer. 
it is like the difference between project explorer and package explorer in the eclipse IDE. Have we to implement the rename refactoring on other files on our own, if we use the ltk refactoring?
I also wan't to switch

         <popupMenu
               allowsPlatformContributions="true"

to false to remove the team, compare menues from the context menu.
We then need to change the way how we provide the run menu for tcl, tsl and folders.

**Comment by kpanier** [comment]
You can use the te test from this branch.

**Comment by franzbecker** [comment]
Obselete with https://github.com/test-editor/test-editor-xtext/pull/148

**Pull request closed without merging**
